# Site settings
title: Elselab
email: projects@elselab.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elselab.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
